version: "3.8"

services:
  kafka:
    image: confluentinc/cp-kafka:7.8.5
    container_name: kafka
    ports:
      - "9092:9092"
    user: "0:0"
    environment:
      KAFKA_KRAFT_MODE: "true"
      CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka-network

  php-kafka:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php-kafka-dev
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - kafka
    networks:
      - kafka-network
    stdin_open: true
    tty: true

volumes:
  kafka-data:

networks:
  kafka-network:
    driver: bridge